### ISSUE TITLE
Function doesn't work properly with quote characters

### ISSUE THREAD

**Issue by jakebox** [samrawal/gpt-macro#2]
Bit of an oversight on my part I guess, though I hadn't tried this with the Python version. The function doesn't parse input properly properly when it contains `"` or `'`.

I don't have time to fix this at the moment but can try myself later next month if it's not fixed by then!

**Comment by samrawal** [comment]
Thanks for noticing this! I pushed a small commit [0] that adds escape characters to double quotes in a user's selection -- I believe this resolves any issues w.r.t. _sending_ data containing `'` or `"` through the API call. The other thing remaining is to sanitize the returned values from the API in a similar manner.

[0] https://github.com/samrawal/gpt-emacs-macro/commit/73442dea6da4ebb995aa0047c997e98946ac09f7

**Comment by samrawal** [comment]
Reverted back to Python implementation for now, but functionally this issue is properly handled now.
